package com.bms.BookMyShow.dto;

public enum CastType {
  LeadActor,
  LeadActress,
  SupportingActor,
  SupportingActress,
  CharacterActor,
  CharacterActress,
  Antagonist,
  Villain,
  Protagonist,
  Hero,
  Cameo,
  Extra,
  VoiceActor,
  StuntPerformer,
  DoublesAndStandIns,
  Narrator,
  Host,
  Presenter,
  EnsembleCast,
  ChildActor,
  Older,
  YouthVersions,
  BackgroundPerformers,
  AnimalActors,
  PrincipalActor,
  PrincipalActress,
  ComedicRelief,
  LoveInterest,
}
